[package]
name = "synth-emulator"
version = "0.3.0"
authors = ["Hiromasa Tanaka <h1romas4@gmail.com>"]
edition = "2018"

[lib]
path = "src/rust/lib.rs"

[dependencies]
flate2 = "1.0"
nom = "5"
serde = "1"
serde_json = "1"
serde_derive = "1"
